AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/rubocop
    - spec/**/*

Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 12

Metrics/ModuleLength:
  Max: 160

Metrics/ClassLength:
  Max: 160

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Naming/FileName:
  Exclude:
    - lib/ssh-tunnel.rb
