plugins:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - bin/*
    - spec/**/*

Gemspec/RequireMFA:
  Enabled: false

########
# LINT #
########

Lint/UselessConstantScoping:
  Enabled: false

#########
# STYLE #
#########

Style/Documentation:
  Enabled: false

Style/CommandLiteral:
  EnforcedStyle: percent_x

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

###########
# METRICS #
###########

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 12

Metrics/ModuleLength:
  Max: 160

Metrics/ClassLength:
  Max: 160

##########
# LAYOUT #
##########

Layout/LineLength:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

##########
# NAMING #
##########

Naming/FileName:
  Exclude:
    - lib/ssh-tunnel.rb
