---
name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 4 1 * *'
  # Run workflow manually
  workflow_dispatch:

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.4'
          - '3.3'
          - '3.2'
          - 'head'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update APT
        run: |
          sudo apt-get update
          sudo apt-get install -y libgirepository1.0-dev libgdk-pixbuf2.0-dev

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          # We cannot use bundler cache here:
          # Failure/Error: require 'gtk3'
          # GObjectIntrospection::RepositoryError::TypelibNotFound:
          #   Typelib file for namespace 'Atk' (any version) not found
          # bundler-cache: true

      - name: Bundle install
        run: bundle install

      - name: Fake screen
        run: Xvfb :99 &

      - name: RSpec & publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          DISPLAY: ':99'
        with:
          coverageCommand: bin/rspec
