---
name: CI

on:
  - push
  - pull_request

jobs:
  rspec:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.7.x
          - 2.6.x
          - 2.5.x
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Bundle
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: RSpec
        run: |
          Xvfb :99 &
          export DISPLAY=:99
          bundle exec rake
