---
name: CI

on:
  - push
  - pull_request

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.3'
          - '3.2'
          - '3.1'
          - 'head'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update APT
        run: |
          sudo apt-get update
          sudo apt-get install -y libgirepository1.0-dev

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Bundle install
        run: bundle install

      - name: Fake screen
        run: Xvfb :99 &

      - name: RSpec & publish code coverage
        uses: paambaati/codeclimate-action@v8.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          DISPLAY: ':99'
        with:
          coverageCommand: bin/rake
