---
name: CI

on:
  - push
  - pull_request

jobs:
  rspec:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.1'
          - '3.0'
          - '2.7'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update APT
        run: |
          sudo apt-get update
          sudo apt-get install -y libgirepository1.0-dev

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          cache-version: 1

      - name: Fake screen
        run: Xvfb :99 &

      - name: RSpec & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          DISPLAY: ':99'
        with:
          coverageCommand: bin/rake
